FROM base-swift-ubuntu:latest

RUN ansible-playbook -i "localhost," -c local /usr/local/src/swift/tools/docker_test_target/playbooks/setup_proxy.yaml

ENTRYPOINT ["swift-proxy-server", "/etc/swift/proxy-server.conf"]
