FROM base-swift-ubuntu:latest

RUN ansible-playbook -i "localhost," -c local /usr/local/src/swift/tools/docker_test_target/playbooks/setup_container.yaml

ENTRYPOINT ["swift-container-server", "/etc/swift/container-server.conf"]
