[DEFAULT]
bind_ip = 127.0.0.1
bind_port = 6205
workers = 1
user = <your-user-name>
log_facility = LOG_LOCAL1
eventlet_debug = true

[ring-manager-agent]
mode = enforce
ring_manager_urls = http://127.0.0.1:6205
shuffle_ring_manager_urls = false
read_key = changeme-read
