[DEFAULT]
bind_ip = 127.0.0.1
bind_port = 6205
workers = 1
user = <your-user-name>
log_facility = LOG_LOCAL1
eventlet_debug = true

[pipeline:main]
pipeline = catch_errors healthcheck ring-manager-auth ring-manager-server

[app:ring-manager-server]
use = egg:swift#ring_manager
log_requests = true
ring_manager_state_dir = /etc/swift/ring-manager-state
ring_builder_dir = /etc/swift
max_explicit_device_id = 1000000
max_json_request_body_size = 1048576
max_partitions_at_risk_selectors = 1000
builder_lock_timeout = 600

[filter:ring-manager-auth]
use = egg:swift#ring_manager_auth
admin_key = changeme
read_key = changeme-read

[filter:healthcheck]
use = egg:swift#healthcheck

[filter:catch_errors]
use = egg:swift#catch_errors
